### ISSUE TITLE
in-arguments.py needs non-documented dependencies

### ISSUE THREAD

**Issue by VorpalBlade** [shagabutdinov/sublime-context#1]
According to the readme.md file, this Sublime plugin have no dependencies. in-arguments.py however needs your Expression and Statement libraries. This should probably be documented.

**Comment by shagabutdinov** [comment]
I moved it to separate package: didn't want to overload "context" plugin with unnecessary dependencies.

**Comment by shagabutdinov** [comment]
Closed in 369b45c7a9349d516a61f43163a1b29427d6b96b
